set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-ghostty:RGB"

# underline styles (undercurl)
set -ga terminal-features ",xterm-ghostty:usstyle"
set -ga terminal-features ",tmux-256color:usstyle"

set-option -g status-style bg=default
set-option -g status-style fg=default
set-option -g status-position top
set -g extended-keys on
set -g extended-keys-format csi-u

set -g prefix M-d
unbind C-b
bind-key M-d send-prefix

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r J resize-pane -D 100
bind -r K resize-pane -U 100
bind -r L resize-pane -R 100
bind -r H resize-pane -L 100

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection 'clipboard'
# set -g @plugin 'den-tanui/tmux-agent-sidebar#feat/pi-integration'

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 1 # transparent background
# set -g @plugin '2kabhishek/tmux2k'
# set -g @tmux2k-theme 'catppuccin'
# set -g @tmux2k-icons-only true
# set -g @tmux2k-bg-main 'default'
# set -g @tmux2k-bg-alt 'default'
# set -g @tmux2k-black 'default'
# set -g @tmux2k-message-bg 'default'
# set -g @tmux2k-message-fg 'default'
# set -g @tmux2k-window-list-alignment 'centre'
#
# set -g @tmux2k-left-plugins "session"
# set -g @tmux2k-right-plugins "cpu ram"
# set -g @tmux2k-prefix-highlight '#333333'  # red background on prefix activation

# Popups
# bind s display-popup -E -w 20% -h 25% "~/.config/tmux/scripts/session-switcher.sh"
# bind n display-popup -E -w 20% -h 15% "~/.config/tmux/scripts/session-new.sh"
# bind d display-popup -E -w 20% -h 25% "~/.config/tmux/scripts/session-delete.sh"
bind g display-popup -E -w 100% -h 100% -d "#{pane_current_path}" "lazygit"
bind z display-popup -E -w 100% -h 100% "lazysql"
bind G display-popup -E -w 100% -h 100% -d "#{pane_current_path}" "~/.config/tmux/scripts/git-diff-all.sh | dv"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '/opt/homebrew/opt/tpm/share/tpm/tpm'
