onboarding = false

[theme]
name = "vesper"

[ui]
show_agent_labels_on_pane_borders = true
sidebar_width = 40
agent_panel_scope = "all"
accent = "green"

[keys]
prefix = "alt+d"
new_workspace = "n"
rename_workspace = "shift+n"
close_workspace = "X"
reload_config = "R"      # optional, unset by default
open_notification_target = "" # optional, unset by default
new_tab = "c"
split_vertical = "|"
split_horizontal = "-"
close_pane = "x"
rename_pane = ""        # optional, unset by default
fullscreen = "f"
resize_mode = "r"
toggle_sidebar = "b"
previous_workspace = "ctrl+alt+["
next_workspace = "ctrl+alt+]"
previous_agent = "ctrl+["
next_agent = "ctrl+]"
rename_tab = "T" 

[keys.indexed]
tabs = "ctrl"
agents = "ctrl+shift"

[[keys.command]]
key = "d"
type = "pane"
command = "lazydocker"

[[keys.command]]
key = "g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "z"
type = "pane"
command = "lazysql"

[[keys.command]]
key = "G"
type = "pane"
command = "~/.config/tmux/scripts/git-diff-all.sh | diffnav"

