onboarding = false

[theme]
name = "tokyo-night"
auto_switch = true
light_name = "tokyo-night-day"
dark_name = "tokyo-night"

[ui]
sidebar_width = 32
sidebar_min_width = 18
sidebar_max_width = 36
sidebar_collapsed_mode = "hidden"
mouse_capture = true
confirm_close = true
prompt_new_tab_name = true
show_agent_labels_on_pane_borders = true
pane_borders = true
pane_gaps = false

# accent = "green"

[keys]
prefix = "alt+d"
new_tab = "prefix+c"
split_horizontal = "prefix+minus"
detach = "prefix+q"
workspace_picker = "prefix+w"
new_workspace = "prefix+n"
rename_workspace = "prefix+shift+w"
close_workspace = "prefix+shift+d"
previous_tab = "prefix+ctrl+H"
next_tab = "prefix+ctrl+L"
switch_tab = "ctrl+1..9"
switch_workspace = "ctrl+shift+1..9"
navigate_workspace_up =  "up"
navigate_workspace_down = "down" 
rename_tab = "prefix+shift+t"
close_tab = "prefix+shift+x"
split_vertical = "prefix+|"
close_pane = "prefix+x"
zoom = "prefix+z"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"
new_worktree = "prefix+t"
goto = "prefix+p"

[[keys.command]]
key = "prefix+d"
type = "pane"
command = "lazydocker"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+S"
type = "pane"
command = "sabiql"

[[keys.command]]
key = "prefix+E"
type = "pane"
command = "nvim"

[[keys.command]]
key = "prefix+G"
type = "pane"
command = "dv"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "herdr-splits.nav-left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "herdr-splits.nav-down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "herdr-splits.nav-up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "herdr-splits.nav-right"

[[keys.command]]
key = "ctrl+shift+h"
type = "plugin_action"
command = "herdr-splits.resize-left"

[[keys.command]]
key = "ctrl+shift+j"
type = "plugin_action"
command = "herdr-splits.resize-down"

[[keys.command]]
key = "ctrl+shift+k"
type = "plugin_action"
command = "herdr-splits.resize-up"

[[keys.command]]
key = "ctrl+shift+l"
type = "plugin_action"
command = "herdr-splits.resize-right"

[[keys.command]]
key = "cmd+r"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"

[ui.toast]
delivery = "herdr"

[update]
channel = "preview"
